// The code workspace: where spec-implementer's generated product lives.
//
// It is deliberately OUTSIDE this git repository. The repo root holds the
// user's own untracked work (reelbanao/, projects/, research-archive/), and
// untracked means unrecoverable — a code-writing agent running under
// `permissionMode: 'bypassPermissions'` must not be pointed anywhere near it.
// Generated code therefore goes to ~/agent-pipeline-workspace by default, in
// its own git history, overridable with PIPELINE_WORKSPACE.
//
// Everything here is orchestrator-side. The agent has no shell (see
// agents/spec-implementer.md and docs/lld.md LD-1), so bootstrapping, git,
// dependency installation (orchestrator/deps.ts) and typechecking are all run by
// this process, never by the agent.

import { execFile } from "node:child_process";
import { mkdir, readdir, readFile, stat, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { promisify } from "node:util";
import { PROJECT_ROOT } from "./agent-loader.js";

const execFileAsync = promisify(execFile);

/** Default workspace location when PIPELINE_WORKSPACE is not set. */
const DEFAULT_WORKSPACE_DIR = path.join(os.homedir(), "agent-pipeline-workspace");

/** Directories never walked when snapshotting or scanning the workspace. */
const IGNORED_DIRS = new Set([".git", "node_modules", "dist", ".next", "build", "coverage"]);

/** Orchestrator-owned bookkeeping files; not part of the generated product. */
export const PROGRESS_JSON = "pipeline-progress.json";
export const PROGRESS_MD = "PROGRESS.md";
/**
 * Where orchestrator/deps.ts records the hash of the last dependency set it
 * successfully installed. Lives in the workspace because that is what the fact
 * is about — this workspace's `node_modules` — and is excluded from
 * `changedFiles()` like the other two, so it can never be mistaken for output
 * the agent wrote.
 */
export const INSTALL_STATE_FILE = ".pipeline-install-state.json";

/**
 * Where generated code goes. Resolved once per process so every caller agrees,
 * and resolved to an absolute path so it can be handed to the SDK as `cwd`.
 */
export function workspaceRoot(): string {
  const fromEnv = process.env.PIPELINE_WORKSPACE;
  const chosen =
    typeof fromEnv === "string" && fromEnv.trim().length > 0 ? fromEnv.trim() : DEFAULT_WORKSPACE_DIR;
  return path.resolve(chosen.startsWith("~") ? chosen.replace(/^~/, os.homedir()) : chosen);
}

/**
 * The workspace tsconfig.
 *
 * Two non-obvious choices, both forced by the same fact — the agent has no
 * shell, so it can never run `npm install` itself:
 *
 *  - `typeRoots` lists THIS repo's installed `@types` alongside the workspace's
 *    own `node_modules/@types`. Without this repo's copy, every generated file
 *    that touches `process`/`Buffer`/`console` fails on TS2304 "cannot find
 *    name" before any dependency install has happened, which would make the
 *    typecheck verifier reject every module for a reason that has nothing to do
 *    with the module. The workspace's own entry comes first so a `@types/node`
 *    the generated product actually declared wins over this repo's version.
 *  - `lib` includes DOM for the same reason on the browser side.
 *
 * Third-party imports resolve only once orchestrator/deps.ts has installed the
 * dependencies the agent declared in package.json. Until then they surface as
 * TS2307, which the verifier downgrades to a warning; after a successful
 * install a TS2307 means an UNDECLARED import and fails the module. See
 * classifyTypecheck and verifyModule.
 */
function workspaceTsconfig(): string {
  const typeRoots = path.join(PROJECT_ROOT, "node_modules", "@types");
  return `${JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        module: "NodeNext",
        moduleResolution: "NodeNext",
        lib: ["ES2022", "DOM"],
        strict: true,
        noEmit: true,
        skipLibCheck: true,
        esModuleInterop: true,
        allowSyntheticDefaultImports: true,
        forceConsistentCasingInFileNames: true,
        resolveJsonModule: true,
        typeRoots: ["./node_modules/@types", typeRoots],
      },
      include: ["**/*.ts", "**/*.tsx"],
      exclude: ["node_modules", "dist"],
    },
    null,
    2
  )}\n`;
}

function workspacePackageJson(): string {
  return `${JSON.stringify(
    {
      name: "agent-pipeline-product",
      version: "0.0.0",
      private: true,
      type: "module",
      description:
        "Generated by the agent-pipeline spec-implementer stage. Not hand-written; see PROGRESS.md.",
      scripts: { typecheck: "tsc --noEmit" },
    },
    null,
    2
  )}\n`;
}

async function pathExists(target: string): Promise<boolean> {
  try {
    await stat(target);
    return true;
  } catch {
    return false;
  }
}

/** Writes `contents` only if `file` is absent. Never clobbers existing work. */
async function writeIfAbsent(file: string, contents: string): Promise<boolean> {
  if (await pathExists(file)) return false;
  await writeFile(file, contents, "utf-8");
  return true;
}

export interface WorkspaceBootstrapReport {
  root: string;
  created: string[];
}

/**
 * Creates the workspace if it does not exist, and fills in only the pieces that
 * are missing. Idempotent by construction: a second run reports an empty
 * `created` list and touches nothing, so resuming a partially-built product is
 * safe.
 */
export async function ensureWorkspace(): Promise<WorkspaceBootstrapReport> {
  const root = workspaceRoot();
  const created: string[] = [];

  if (!(await pathExists(root))) {
    await mkdir(root, { recursive: true });
    created.push(`${root}/`);
  }

  if (await writeIfAbsent(path.join(root, "package.json"), workspacePackageJson())) {
    created.push("package.json");
  }
  if (await writeIfAbsent(path.join(root, "tsconfig.json"), workspaceTsconfig())) {
    created.push("tsconfig.json");
  }
  // node_modules/ must stay ignored: orchestrator/deps.ts installs the
  // dependencies the agent declared into the workspace, and committing a
  // model-chosen dependency tree into the generated product's history is not
  // something anyone asked for.
  const gitignore = "node_modules/\ndist/\n";
  if (await writeIfAbsent(path.join(root, ".gitignore"), gitignore)) {
    created.push(".gitignore");
  }

  // Its own history, separate from the pipeline repo's. `git init` is itself
  // idempotent, but checking first keeps `created` honest.
  if (!(await pathExists(path.join(root, ".git")))) {
    try {
      await execFileAsync("git", ["init", "--quiet"], { cwd: root });
      created.push(".git/");
    } catch (err) {
      const detail = err instanceof Error ? err.message : String(err);
      console.warn(`  [workspace] git init failed (continuing without version control): ${detail}`);
    }
  }

  return { root, created };
}

/** size+mtime of every non-ignored file, keyed by workspace-relative path. */
export type WorkspaceSnapshot = Map<string, string>;

async function walk(dir: string, root: string, into: WorkspaceSnapshot): Promise<void> {
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return;
  }
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (IGNORED_DIRS.has(entry.name)) continue;
      await walk(full, root, into);
      continue;
    }
    if (!entry.isFile()) continue;
    try {
      const info = await stat(full);
      into.set(path.relative(root, full), `${info.size}:${info.mtimeMs}`);
    } catch {
      // Raced with a delete; simply absent from this snapshot.
    }
  }
}

/** Snapshots the workspace so a later diff can prove a call wrote something. */
export async function snapshotWorkspace(): Promise<WorkspaceSnapshot> {
  const root = workspaceRoot();
  const snapshot: WorkspaceSnapshot = new Map();
  await walk(root, root, snapshot);
  return snapshot;
}

/**
 * Files created or modified between two snapshots, as workspace-relative paths.
 * Orchestrator bookkeeping files — the ledger, PROGRESS.md and the dependency
 * install state — are excluded so they can never be mistaken for the agent's
 * output. Deletions are ignored: the question this answers is
 * "did this call write anything", not "what changed".
 */
export function changedFiles(before: WorkspaceSnapshot, after: WorkspaceSnapshot): string[] {
  const changed: string[] = [];
  for (const [file, fingerprint] of after) {
    if (file === PROGRESS_JSON || file === PROGRESS_MD || file === INSTALL_STATE_FILE) continue;
    if (before.get(file) !== fingerprint) changed.push(file);
  }
  return changed.sort();
}

export interface TypecheckResult {
  /** Process exit code; 0 means tsc found nothing at all. */
  exitCode: number;
  /** Diagnostics for unresolved imports (TS2307) — downgraded to warnings. */
  missingModuleWarnings: string[];
  /** Every other diagnostic line — any of these fails the module. */
  errors: string[];
  /** Raw tsc output, kept for the progress log when something fails. */
  raw: string;
}

/** `src/a.ts(3,25): error TS2307: Cannot find module 'zod'...` */
const DIAGNOSTIC_RE = /error TS(\d+):/;

/**
 * Splits tsc output into "missing dependency" noise and real errors.
 *
 * TS2307 ("Cannot find module X or its corresponding type declarations") gets
 * its own bucket because its MEANING depends on whether a dependency install has
 * succeeded, which this function has no business knowing. Unresolved-import
 * lines are separated here; verifyModule decides whether they are the expected
 * consequence of an uninstalled workspace (a warning) or an import the agent
 * never declared in package.json (a failure). Every other diagnostic code is a
 * genuine defect in generated code and fails the module unconditionally.
 *
 * Only lines containing `error TS<number>:` are classified; tsc's indented
 * continuation lines are left in `raw` and counted against neither bucket.
 */
export function classifyTypecheck(exitCode: number, output: string): TypecheckResult {
  const missingModuleWarnings: string[] = [];
  const errors: string[] = [];

  for (const line of output.split(/\r?\n/)) {
    const match = DIAGNOSTIC_RE.exec(line);
    if (match === null) continue;
    if (match[1] === "2307") missingModuleWarnings.push(line.trim());
    else errors.push(line.trim());
  }

  return { exitCode, missingModuleWarnings, errors, raw: output };
}

/**
 * Runs `tsc --noEmit` against the workspace, using this repo's TypeScript
 * binary (the workspace's own `node_modules`, when deps.ts has populated it,
 * holds the generated product's dependencies, not a compiler we want to run).
 * This is the orchestrator's own check — success is never the agent's
 * self-report.
 */
export async function typecheckWorkspace(): Promise<TypecheckResult> {
  const root = workspaceRoot();
  const tsc = path.join(PROJECT_ROOT, "node_modules", "typescript", "bin", "tsc");

  try {
    const { stdout, stderr } = await execFileAsync(
      process.execPath,
      [tsc, "--noEmit", "--pretty", "false", "-p", path.join(root, "tsconfig.json")],
      { cwd: root, maxBuffer: 32 * 1024 * 1024 }
    );
    return classifyTypecheck(0, `${stdout}${stderr}`);
  } catch (err) {
    const failure = err as { code?: unknown; stdout?: unknown; stderr?: unknown; message?: unknown };
    const stdout = typeof failure.stdout === "string" ? failure.stdout : "";
    const stderr = typeof failure.stderr === "string" ? failure.stderr : "";
    const combined = `${stdout}${stderr}`;
    const exitCode = typeof failure.code === "number" ? failure.code : 1;
    if (combined.trim().length === 0) {
      // tsc could not be launched at all — that is a config fault, not a
      // module failure, and must not be reported as "the code is fine".
      const detail = typeof failure.message === "string" ? failure.message : String(err);
      return {
        exitCode,
        missingModuleWarnings: [],
        errors: [`tsc could not be run: ${detail}`],
        raw: detail,
      };
    }
    return classifyTypecheck(exitCode, combined);
  }
}

/**
 * Filters a list of workspace-relative paths down to the ones that still exist.
 *
 * Used before telling a retried module to "read and repair the files your last
 * attempt wrote": if a human reverted or deleted that output between runs, the
 * instruction is a lie and sends the agent looking for files that are not there.
 * `stat` rather than a read, because the contents are the agent's job, not ours.
 */
export async function existingWorkspaceFiles(relPaths: readonly string[]): Promise<string[]> {
  const present: string[] = [];
  for (const relPath of relPaths) {
    try {
      await stat(path.join(workspaceRoot(), relPath));
      present.push(relPath);
    } catch {
      // Absent or unreadable: either way it cannot be read and repaired.
    }
  }
  return present;
}

/** Reads a workspace file, returning null when it is unreadable. */
export async function readWorkspaceFile(relPath: string): Promise<string | null> {
  try {
    return await readFile(path.join(workspaceRoot(), relPath), "utf-8");
  } catch {
    return null;
  }
}
